language: csharp

env:
  - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis

sudo: required #false
dist: bionic
dotnet: 2.2.105
mono:
- latest
os:
- linux

branches:
  except:
    - gh-pages

script:
  - ./build.sh Test quick
